# __Introduction to Tensors__

Tensors are fundamental data structures in deep learning and are similar to multi-dimensional arrays. They are a generalization of vectors and matrices to higher dimensions and provide a way to represent and manipulate numerical data efficiently.

Tensors can be seen as containers for numerical data that can be organized into a specific shape or size.

Let's understand how it works.


## Steps to be followed:
1. Import the required libraries
2. Create the rank zero Tensor
3. Create the rank one Tensor
4. Create the rank two Tensor
5. Create the rank three Tensor
6. Convert a Tensor to a NumPy array
7. Perform basic mathematics with Tensors
8. Initialize the Tensor
9. Broadcast the x and y variables

### Step 1: Import the required libraries

- Import two libraries, TensorFlow and NumPy.
- TensorFlow is a popular open-source machine learning framework that provides a set of tools and functionalities for building and training machine learning models.
- NumPy is a Python library for numerical computations that provide support for handling multi-dimensional arrays and mathematical operations on them.

In [1]:
import tensorflow as tf
import numpy as np

### Step 2: Creating the Rank Zero Tensor
- The rank is also known as order, degree, or ndims.
- The **tf.constant(4)** creates a constant Tensor with a single value of **4**.
- The **tf.constant()** function is used to create Tensors with fixed values that cannot be changed.
- The **rank_0_tensor** variable holds the created Tensor.
- The **print(rank_0_tensor)** prints the value of the Tensor, which,  in this case, is __4__.

In [2]:
# Create a scalar tensor of value 4
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


**Observation:**

- As seen above, the output represents a TensorFlow Tensor object with a value of 4, an empty shape, and an **int32** data type.

### Step 3: Creating the Rank One Tensor
- Define a rank one Tensor in TensorFlow with the values **[2.0, 4.0, 5.0]** and print the Tensor object

In [3]:
rank_1_tensor = tf.constant([2.0, 4.0, 5.0])
print(rank_1_tensor)

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float32)


**Observations:**

- As seen above, the output represents a one-dimensional Tensor with three elements: **2.0**, **4.0**, and **5.0**.
- The shape of the Tensor is **(3, ),** indicating that it has a size of 3 along the first dimension.
- The dtype of the Tensor is **float32**, indicating that the elements are of type float.

### Step 4: Creating the Rank Two Tensor
- It creates a rank two Tensor, which is a two-dimensional array, using the **tf.constant** function.
- The Tensor has a shape of (3, 2), meaning it has three rows and two columns, and the elements of the Tensor are specified as [1, 2], [3, 4], and [5, 6].

In [4]:
rank_2_tensor = tf.constant([[1, 2], [3, 4], [5, 6]])
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


**Observations:**

- The output represents a rank two Tensor with a shape of (3, 2) and a dtype of float16. The Tensor contains the following elements arranged in a 3x2 matrix, as seen above.
- Each element of the Tensor is a floating-point number with a precision of 16 bits.

### Step 5: Creating the Rank Three Tensor

- It defines a rank three Tensor with a shape of (3, 2, 5), indicating three layers, each containing two rows and five columns.
- The Tensor represents a 3D array of integers, where each element corresponds to a specific position within the layers, rows, and columns.
- The values increase sequentially from __0__ to __29__, arranged in a structured pattern within the Tensor.



In [5]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


**Observations:**
- The output represents a rank three Tensor with a shape of (3, 2, 5) and a data type of int32.
- It contains three layers, each consisting of two rows and five columns, with integer values ranging from 0 to 29 arranged in a structured pattern within the Tensor.

### Step 6: Convert a Tensor to a NumPy array

- Convert the rank two array present here to a NumPy array.
- The Tensors often contain float datatype.

In [6]:
# Transform rank2 tensor into numpy
rank_2_in_np = rank_2_tensor.numpy()
print(rank_2_in_np)

[[1 2]
 [3 4]
 [5 6]]


**Observations:**
- The output represents a two-dimensional array (matrix) with a shape of (3, 2) and a data type of float16.
- It contains floating-point values ranging from 1.0 to 6.0, organized in three rows and two columns.

### Step 7: Performing Basic Mathematics on Tensors
- Declare two variables **a** and **b**.
- The **tf.add(a, b)** operation performs element-wise addition between Tensors a and b.
- The **tf.multiply(a, b)** operation performs element-wise multiplication between Tensors a and b.
- The **tf.matmul(a, b)** operation performs matrix multiplication between Tensors a and b.


In [7]:
# tensor math
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

print(tf.add(a, b))
print(tf.multiply(a, b))
print(tf.matmul(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [8]:
# Numpy maths
np_a = a.numpy()
np_b = b.numpy()
print(np.add(np_a, np_b))
print(np.multiply(np_a, np_b))
print(np.matmul(np_a, np_b))

[[2 3]
 [4 5]]
[[1 2]
 [3 4]]
[[3 3]
 [7 7]]


**Observations:**
- Tensors do element-wise addition and multiplication.
- The given output consists of three TensorFlow Tensors, each representing a 2x2 matrix with integer values.

  ### Step 8: Initializing the Tensor

  - The **tf.reduce_max(c)** calculates the maximum value in Tensor c.
  - The **tf.math.argmax(c)** returns the index of the maximum value in Tensor c.
  - The **tf.nn.softmax(c)** applies the softmax activation function to Tensor c, which computes the probability distribution over the elements of c.


In [9]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
print(tf.reduce_max(c))
print(tf.math.argmax(c))
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


**Observation:**
- It calculates the maximum value in Tensor c, finds the indices of the maximum values, and applies the softmax function to obtain a probability distribution Tensor.

### Step 9: Broadcasting the X and Y Variables
- Broadcast the two variables **x** and **y**.
- Smaller Tensors are stretched automatically to fit larger Tensors.
- All of these are the same computation.
- It performs element-wise multiplication between Tensors x and a scalar value of 2, between Tensors x and scalar y, and between Tensors x and Tensors z.

In [10]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
print(tf.multiply(x, 2))
print(x * y)
# Since their shapes are exactly the same, TensorFlow performs element-wise multiplication
# directly, without needing to reshape or broadcast.
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


**Observations:**

- We can see that even though the shape of y is not the same as that of x, we can still multiply these two variables.
- So, this is an example of broadcasting, where smaller Tensors are stretched automatically to fit larger Tensors.

#### Reshaping Tensors

In [11]:
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


**Observation:**
- The `shape` function returns a tensor-shaped object that shows the size along each axis.

In [13]:
reshaped = tf.reshape(x , [1,3])

In [ ]:
print(x.shape)
print(reshaped.shape)

In [ ]:
print(x)
print(" ")
print(reshaped)

**Observation:**
- The Tensor has been reshaped to the desired dimensions, providing the intended configuration.

#### Different Types of Tensors
- **Ragged Tensor**: Tensor with the variable number of
elements along some axes is called Ragged Tensor.

A RaggedTensor is a tensor with one or more ragged dimensions, which are dimensions whose slices may have different lengths.

In [ ]:
ragged_list = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]]

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)
print(f"ragged tensor shape: {ragged_tensor.shape}")

- **Scalar String Tensor**: It is a datatype, which means that data can be represented as strings (variable-length byte arrays) in Tensors.

In [ ]:
scalar_string_tensor = tf.constant("gray wolf")
print(scalar_string_tensor)
print(f"string tensor shape: {scalar_string_tensor.shape}")

**Observation**
- We can represent
the strings as Tensors.
